services:
  - type: web
    name: deepsheek-portail-association
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_KEY
        sync: false
